apiVersion: v1
kind: ConfigMap
metadata:
  name: nvd-view-config
data:
  host_addr: https://nvd-controller:8080/v1/cve/nvd_web_front/

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvd-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvd-view
  template:
    metadata:
      labels:
        app: nvd-view
    spec:
      containers:
      - name: nvd-view
        image: erakhi/nvd-view:0.1
        ports:
        - containerPort: 8082
        envFrom:
          - configMapRef:
              name: nvd-view-config
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000


---


apiVersion: v1
kind: Service
metadata:
  name: nvd-view
spec:
  selector:
    app: nvd-view
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: NodePort


